version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: app_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminio
      MONGO_INITDB_ROOT_PASSWORD: adminio
      MONGO_INITDB_DATABASE: adminio
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  redis:
    image: redis:latest
    container_name: app_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2023-01-20T02-05-44Z
    container_name: app_minio
    ports:
      - "9000:9000"
      - "34247:34247"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin123
    command: server /data0 --console-address ":34247"